export const dataUsers = {
  count: 134,
  data: [
    {
      id: 1,
      name: 'Daniel Pearson1',
      email: 'daniel.pearson1@eviden.net',
      role: 'Role User',
      company: 'Eviden',
      buAccess: 'All',
      status: 'Active',
      mobileNr: '+01 9876543210',
      factorAuth: true,
      emailMessage: true,
      smsMessage: true,
      createdBy: 'Eviden (Role_User)',
      createdDate: 'Sep 23, 2023 at 21:10:50',
      updateBy: 'Eviden (Role_User)',
      updatedDate: 'Sep 23, 2023 at 21:10:50',
    },
    {
      id: 2,
      name: 'Daniel Pearson2',
      email: 'daniel.pearson2@eviden.net',
      role: 'Partner Account',
      company: 'Eviden',
      buAccess: 'All',
      status: 'Active',
      mobileNr: '+01 9876543210',
      factorAuth: true,
      emailMessage: true,
      smsMessage: true,
      createdBy: 'Eviden (Role_User)',
      createdDate: 'Sep 23, 2023 at 21:10:50',
      updateBy: 'Eviden (Role_User)',
      updatedDate: 'Sep 23, 2023 at 21:10:50',
    },
    {
      id: 3,
      name: 'Daniel Pearson3',
      email: 'daniel.pearson3@eviden.net',
      role: 'Customer Account',
      company: 'Eviden',
      buAccess: 'All',
      status: 'Active',
      mobileNr: '+01 9876543210',
      factorAuth: true,
      emailMessage: true,
      smsMessage: true,
      createdBy: 'Eviden (Role_User)',
      createdDate: 'Sep 23, 2023 at 21:10:50',
      updateBy: 'Eviden (Role_User)',
      updatedDate: 'Sep 23, 2023 at 21:10:50',
    },
    {
      id: 4,
      name: 'Daniel Pearson4',
      email: 'daniel.pearson4@eviden.net',
      role: 'Role User',
      company: 'Eviden',
      buAccess: 'All',
      status: 'Active',
      mobileNr: '+01 9876543210',
      factorAuth: true,
      emailMessage: true,
      smsMessage: true,
      createdBy: 'Eviden (Role_User)',
      createdDate: 'Sep 23, 2023 at 21:10:50',
      updateBy: 'Eviden (Role_User)',
      updatedDate: 'Sep 23, 2023 at 21:10:50',
    },
    {
      id: 5,
      name: 'John Doe',
      email: 'john.doe@eviden.net',
      role: 'Role User',
      company: 'Eviden',
      buAccess: '2 out of 14',
      status: 'Active',
      mobileNr: '+01 99999',
      factorAuth: true,
      emailMessage: true,
      smsMessage: true,
      createdBy: 'Eviden (Role_User)',
      createdDate: 'Sep 23, 2023 at 21:10:50',
      updateBy: 'Eviden (Role_User)',
      updatedDate: 'Sep 23, 2023 at 21:10:50',
    },
    {
      id: 6,
      name: 'John Doe2',
      email: 'john.doe2@eviden.net',
      role: 'Role User',
      company: 'Eviden',
      buAccess: '2 out of 14',
      status: 'Pending Activation',
      mobileNr: '+01 9876543210',
      factorAuth: true,
      emailMessage: true,
      smsMessage: true,
      createdBy: 'Eviden (Role_User)',
      createdDate: 'Sep 23, 2023 at 21:10:50',
      updateBy: 'Eviden (Role_User)',
      updatedDate: 'Sep 23, 2023 at 21:10:50',
    },
    {
      id: 7,
      name: 'John Doe3',
      email: 'john.doe3@eviden.net',
      role: 'Role User',
      company: 'Eviden',
      buAccess: '2 out of 14',
      status: 'Disabled',
      mobileNr: '+01 9876543210',
      factorAuth: true,
      emailMessage: true,
      smsMessage: true,
      createdBy: 'Eviden (Role_User)',
      createdDate: 'Sep 23, 2023 at 21:10:50',
      updateBy: 'Eviden (Role_User)',
      updatedDate: 'Sep 23, 2023 at 21:10:50',
    },
    {
      id: 8,
      name: 'John Doe4',
      email: 'john.doe4@eviden.net',
      role: 'Role User',
      company: 'Eviden',
      buAccess: 'Denied',
      status: 'Inactive',
      mobileNr: '+01 9876543210',
      factorAuth: true,
      emailMessage: true,
      smsMessage: true,
      createdBy: 'Eviden (Role_User)',
      createdDate: 'Sep 23, 2023 at 21:10:50',
      updateBy: 'Eviden (Role_User)',
      updatedDate: 'Sep 23, 2023 at 21:10:50',
    },
    {
      id: 7,
      name: 'John Doe3',
      email: 'john.doe3@eviden.net',
      role: 'Role User',
      company: 'Eviden',
      buAccess: 'All',
      status: 'Active',
      mobileNr: '+01 9876543210',
      factorAuth: true,
      emailMessage: true,
      smsMessage: true,
      createdBy: 'Eviden (Role_User)',
      createdDate: 'Sep 23, 2023 at 21:10:50',
      updateBy: 'Eviden (Role_User)',
      updatedDate: 'Sep 23, 2023 at 21:10:50',
    },
  ],
};
